"""add switches

Revision ID: 9e58cc19faa5
Revises: 0014a9704849
Create Date: 2025-05-10 20:23:13.908960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e58cc19faa5'
down_revision: Union[str, None] = '0014a9704849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traffic', sa.Column('switched_from', sa.String(), nullable=True))
    op.add_column('traffic', sa.Column('switch_reason', sa.String(), nullable=True))
    op.add_column('traffic', sa.Column('switch_time', sa.Float(), nullable=False))
    op.add_column('traffic', sa.Column('switch_packet_loss', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traffic', 'switch_packet_loss')
    op.drop_column('traffic', 'switch_time')
    op.drop_column('traffic', 'switch_reason')
    op.drop_column('traffic', 'switched_from')
    # ### end Alembic commands ###
