"""alter models

Revision ID: 32408d377afc
Revises: ed71c51c1d56
Create Date: 2025-05-15 18:45:13.997153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32408d377afc'
down_revision: Union[str, None] = 'ed71c51c1d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('optimization_actions', sa.Column('slug', sa.String(), nullable=False))
    op.add_column('optimization_actions', sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('optimization_actions', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_optimization_actions_slug'), 'optimization_actions', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_optimization_actions_slug'), table_name='optimization_actions')
    op.drop_column('optimization_actions', 'is_active')
    op.drop_column('optimization_actions', 'effective_until')
    op.drop_column('optimization_actions', 'slug')
    # ### end Alembic commands ###
