"""traffic model

Revision ID: 54ea3729ce2c
Revises: 
Create Date: 2025-04-22 17:08:18.788378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ea3729ce2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('bandwidth', sa.Float(), nullable=False),
    sa.Column('latency', sa.Float(), nullable=False),
    sa.Column('packet_loss', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_node_id'), 'traffic', ['node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_node_id'), table_name='traffic')
    op.drop_table('traffic')
    # ### end Alembic commands ###
