"""alter traffic

Revision ID: 0014a9704849
Revises: 4639522c7124
Create Date: 2025-05-10 18:33:17.928358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0014a9704849'
down_revision: Union[str, None] = '4639522c7124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traffic', sa.Column('capacity_mbps', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traffic', 'capacity_mbps')
    # ### end Alembic commands ###
