"""add traffic field

Revision ID: 4639522c7124
Revises: 54ea3729ce2c
Create Date: 2025-04-22 18:11:53.691985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4639522c7124'
down_revision: Union[str, None] = '54ea3729ce2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traffic', sa.Column('node_type', sa.String(), nullable=False))
    op.alter_column('traffic', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_traffic_node_type'), 'traffic', ['node_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_node_type'), table_name='traffic')
    op.alter_column('traffic', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('traffic', 'node_type')
    # ### end Alembic commands ###
